# Generated by Django 4.1.5 on 2023-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='createdbyid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='createddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='lastmodifiedbyid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='table1',
            name='lastmodifieddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
