# Generated by Django 4.1.5 on 2023-02-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_apis_app', '0002_table1_createdbyid_table1_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table4',
            name='parentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='django_apis_app.table3'),
        ),
        migrations.AlterField(
            model_name='table4',
            name='ultimateparentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_parent', to='django_apis_app.table3'),
        ),
    ]
