# Generated by Django 4.1.5 on 2023-04-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apis_app', '0003_alter_table4_parentid_alter_table4_ultimateparentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='id',
            field=models.BigIntegerField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table2',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='table3',
            name='id',
            field=models.BigIntegerField(max_length=38, primary_key=True, serialize=False),
        ),
    ]
